### ISSUE TITLE
Microsoft Azure email reporting that Almalinux-hpc 8.7 image is to be deprecated Dec 30th 2024?

### ISSUE THREAD

**Issue by garymansellricardo** [Azure/cyclecloud-slurm#282]
We are using AlmaLinux HPC 8.7 images for our CycleCloud (8.6.4 - latest) Slurm cluster nodes in production and I received an email from Microsoft today that they are to be deprecated on Dec 30th 2024.

I understand from the azhpc images team (via a Github Issue) that they have published an AlmaLinux 8.10 HPC image.

What are the plans for Azure CycleCloud (specifically Slurm Clusters) to be able to spin up nodes using this new 8.10 image instead of the current 8.7 one?

Please can you urgently advise?

**Comment by aditigaur4** [comment]
Hello,

We are aware of this and Cyclecloud next release would point to almalinux 8.10 but you dont need to wait until then. You can lookup the offer and sku information for the 8.10 hpc image using `az vm images` cli and click on "custom image" tab on your image selection. This is described here:

https://learn.microsoft.com/en-us/azure/cyclecloud/how-to/create-custom-image?view=cyclecloud-8

**Comment by aditigaur4** [comment]
FYI cyclecloud next release is due nov first week

**Comment by darkwhite29** [comment]
Current AlmaLinux 8.10 HPC image URN, FYI:

almalinux:almalinux-hpc:8_10-hpc-gen1:8.10.2024092301
almalinux:almalinux-hpc:8_10-hpc-gen2:8.10.2024092301

**Comment by garymansellricardo** [comment]
Hi, thanks for getting back to me on this so quickly.

I have just tried switching my scheduler node from the default AlmaLinux 8.7 image to the new Marketplace AlmaLinux HPC 8.10 image (almalinux:almalinux-hpc:8_10-hpc-gen2:latest) as a custom image in my CycleCloud (8.6.1) Slurm (23.02.7-1) cluster config, but the Scheduler node now fails to start, giving the below error in the CC UI:

```
Errno::ENOENT: ruby_block[create pv and vg for builtinsched] (cvolume::default line 137) had an error: Errno::ENOENT: No such file or directory - vgscan
Software Configuration
Review local log files on the VM at /opt/cycle/jetpack/logs
[Get more help on this issue](https://aka.ms/cyclecloud/error-help)
Detail:
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:340:in `exec'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:340:in `block in fork_subprocess'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:318:in `fork'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:318:in `fork_subprocess'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:95:in `run_command'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:267:in `run_command'
/opt/cycle/jetpack/system/chef/cache/cookbooks/cvolume/libraries/cvolume.rb:12:in `existing_vg'
/opt/cycle/jetpack/system/chef/cache/cookbooks/cvolume/recipes/default.rb:140:in `block (3 levels) in from_file'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/provider/ruby_block.rb:31:in `block in action_run'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/provider.rb:216:in `converge_by'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/provider/ruby_block.rb:30:in `action_run'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/provider.rb:171:in `run_action'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/resource.rb:592:in `run_action'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/runner.rb:70:in `run_action'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/runner.rb:98:in `each'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/runner.rb:98:in `block in converge'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/runner.rb:97:in `converge'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/client.rb:718:in `block in converge'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/client.rb:713:in `catch'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/client.rb:713:in `converge'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/client.rb:752:in `converge_and_save'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/client.rb:286:in `run'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application.rb:292:in `block in fork_chef_client'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application.rb:280:in `fork'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application.rb:280:in `fork_chef_client'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application.rb:245:in `block in run_chef_client'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application.rb:233:in `run_chef_client'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application/client.rb:470:in `sleep_then_run_chef_client'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application/client.rb:459:in `block in interval_run_chef_client'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application/client.rb:458:in `loop'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application/client.rb:458:in `interval_run_chef_client'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application/client.rb:442:in `run_application'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application.rb:59:in `run'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/lib/chef/application/solo.rb:225:in `run'
/opt/cycle/jetpack/system/embedded/lib/ruby/gems/2.5.0/gems/chef-13.12.14/bin/chef-solo:25:in `<top (required)>'
/opt/cycle/jetpack/system/embedded/bin/chef-solo:23:in `load'
/opt/cycle/jetpack/system/embedded/bin/chef-solo:23:in `<main>'
```

Any ideas why this may be?

**Comment by garymansellricardo** [comment]
@aditigaur4 - do you see the same problem using the almalinux 8.10 custom image?

**Comment by aditigaur4** [comment]
@garymansellricardo We are tracking this issue. The setup takes a dependency on a binary thats not available on almalinux10. We are releasing a new release end of this month that will fix this issue with almalinux 10

**Comment by garymansellricardo** [comment]
@aditigaur4  - thanks so much for the confirmation, I can rest easy it's not something wrong my end now :-)

I would appreciate if you would update this issue when the new CC version is available so that I can test it to ensure my PROD system still works with the new AlmaLinux 8.10 HPC image before the AlmaLinux 8.7 image EOL's (things are getting a bit close for comfort now as once I have got CC working with 8.10 HPC image, I still need to validate my HPC applications run on it OK).

**Comment by aditigaur4** [comment]
Hello @garymansellricardo  The new marketplace image of cyclecloud includes the almalinux 8.10 image version. That includes the fix for the issue we saw earlier. You an update your current running instance by following the steps here: https://learn.microsoft.com/en-us/azure/cyclecloud/how-to/upgrade-and-migrate?view=cyclecloud-8

After the update start a new slurm cluster which should work with almalinux 8.10 correctly.

**Comment by garymansell** [comment]
Can confirm since updating to CC 8.6.5 - I can now start Alma 8.10 VMs (they are the new default for Alma 8)

Thanks
